"""Category type changed to string

Revision ID: 019e0bb83b4c
Revises: b89b188ea0e8
Create Date: 2025-01-13 11:34:41.734626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '019e0bb83b4c'
down_revision: Union[str, None] = 'b89b188ea0e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'category',
               existing_type=mysql.ENUM('INCOME', 'EXPENSE', 'TRANSFER'),
               type_=sa.String(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'category',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('INCOME', 'EXPENSE', 'TRANSFER'),
               nullable=True)
    # ### end Alembic commands ###
