"""invoice status to enum

Revision ID: 5bd31c977679
Revises: 2c660e1c762b
Create Date: 2025-01-13 20:09:54.610074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5bd31c977679'
down_revision: Union[str, None] = '2c660e1c762b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('invoice_tags_ibfk_1', 'invoice_tags', type_='foreignkey')
    op.drop_constraint('invoice_tags_ibfk_2', 'invoice_tags', type_='foreignkey')
    op.create_foreign_key(None, 'invoice_tags', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key(None, 'invoice_tags', 'invoices', ['invoice_id'], ['id'])
    op.alter_column('invoices', 'status',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.Enum('OVERDUE', 'PAID', 'PENDING', name='invoicestatus'),
               existing_nullable=False)
    op.drop_constraint('invoices_ibfk_1', 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key('invoices_ibfk_1', 'invoices', 'users', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.alter_column('invoices', 'status',
               existing_type=sa.Enum('OVERDUE', 'PAID', 'PENDING', name='invoicestatus'),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=False)
    op.drop_constraint(None, 'invoice_tags', type_='foreignkey')
    op.drop_constraint(None, 'invoice_tags', type_='foreignkey')
    op.create_foreign_key('invoice_tags_ibfk_2', 'invoice_tags', 'tags', ['tag_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('invoice_tags_ibfk_1', 'invoice_tags', 'invoices', ['invoice_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    # ### end Alembic commands ###
