"""resize otp to 100

Revision ID: 6a2cd2996af2
Revises: a38c88504051
Create Date: 2025-01-10 20:13:40.749393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6a2cd2996af2'
down_revision: Union[str, None] = 'a38c88504051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'otp_secret',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'otp_secret',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=True)
    # ### end Alembic commands ###
